import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

export const metadata = {
  title: {
    default: "M.Fayad",
    template: "%s | M.Fayad",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
